### ISSUE TITLE
Should this declare window.ethereum?

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/types#16]
Hi, 

I am working on creating a snap and I want to reference `window.ethereum`in the frontend with the correct types, I added this library hoping to get the type definition but it doesn't appear to exist.

Should it exist here or should I get the type definition for `window.ethereum` elsewhere?

Thanks for any help 🙏

**Comment by mcmire** [comment]
`window.ethereum` isn't available in a snap. It is, however, available, in a dapp. If you're using [`detect-provider`](https://github.com/MetaMask/detect-provider), we have done some [work recently](https://github.com/MetaMask/detect-provider/pull/41) where you can call `detectEthereumProvider`, and the object it resolves with will have a proper type. This isn't available yet in a release but you could copy the type from this PR for now.

**Comment by mcmire** [comment]
Closing since this is a question, but feel free to continue the discussion.
